apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-deployment
  labels:
    app: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend-container
          image: react-frontend:latest
          ports:
            - containerPort: 80
          # AÑADE ESTA LÍNEA AQUÍ
          imagePullPolicy: Never # Le dice a Kubernetes que NO intente extraer la imagen de un registro remoto.
