apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service # Nombre del servicio
  labels:
    app: react-frontend
spec:
  selector:
    app: react-frontend # Selecciona los Pods con esta etiqueta
  ports:
    - protocol: TCP
      port: 80 # Puerto en el que el servicio escuchará (fuera del clúster)
      targetPort: 80 # Puerto del contenedor al que se redirigirá el tráfico
  type: NodePort # Permite acceder al servicio desde una IP y puerto del nodo Minikube
